server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      mvc:
        routes:
          - id: external-auth
            uri: http://104.211.95.241:8080
            predicates:
              - Path=/api/auth/**
          - id: zone-service
            uri: lb://ZONE-SERVICE
            predicates:
              - Path=/api/zones/**
          - id: sensor-service
            uri: lb://SENSOR-SERVICE
            predicates:
              - Path=/api/sensors/**
          - id: automation-service
            uri: lb://AUTOMATION-SERVICE
            predicates:
              - Path=/api/automation/**
          - id: crop-service
            uri: lb://CROP-SERVICE
            predicates:
              - Path=/api/crops/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "9d8f3e6d4b2a1c0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f"