server:
  port: 8085

spring:
  application:
    name: zone-service

  datasource:
    url: jdbc:mysql://localhost:3306/zone_db
    username: root
    password: Ijse@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888

external:
  iot:
    base-url: "http://104.211.95.241:8080/api"
    user:
      username: "myuser"
      password: "123456"